server:
  port: 9090
spring:
  application:
    name: admin-server

#management:
#  context-path: /
#  security:
#    enabled: true
#    roles: SUPERUSER
#
#security:
#  basic:
#    enabled: true
#    path: ${management.context-path}
#  user:
#    name: admin
#    password: admin
#    role: SUPERUSER
#
#endpoints:
#  actuator:
#    enabled: true
#    path: ${management.context-path}
#  shutdown:
#    enabled: true